### ISSUE TITLE
This repository is out of date after Svelte Kit's cli was changed to use vite directly.

### ISSUE THREAD

**Issue by basuke** [sveltejs/kit-sandbox#2]
When I hit `pnpm dev`, the error is displayed:
```
› pnpm dev

> kit-sandbox@0.0.1 dev /path
> node ../kit/packages/kit/src/cli.js dev --port 4567


  ERROR
    Invalid command: dev

  Run `$ svelte-kit --help` for more info.

 ELIFECYCLE  Command failed with exit code 1.
```

because `svelte-kit` 's only subcommand is `sync` now.

**Comment by Conduitry** [comment]
Thanks for the report. I'm actually going to archive this repo, as it wouldn't very useful anymore now that SvelteKit is shipped unbundled anyway. You can just symlink the SvelteKit source directly into whatever project you want to use it in.

**Comment by Rich-Harris** [comment]
I've unarchived it, because I use this repo day-to-day — this _is_ the 'whatever project you want to use it in'. We just need to bring the default branch up to date (I currently use `default-template`, I think the default branch was supposed to use the skeleton template. Should probably just replace the current default with `default-template`)
